site_name: Coherent Recursion
site_description: A modular evolution of Minecraft — lore-rich, resonance-driven, and community-built.
site_author: X18Tec
repo_name: X18Tec/coherent-recursion-docs
repo_url: https://github.com/X18Tec/coherent-recursion-docs

theme:
  name: material
  logo: images/logo.png  # optional
  favicon: images/favicon.ico  # optional
  features:
    - navigation.instant
    - navigation.sections
    - navigation.expand
    - toc.integrate
    - navigation.top
    - search.highlight
    - content.code.annotate
    - content.action.edit

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.emoji
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.snippets
  - pymdownx.tasklist

nav:
  - Home: module-contributor-guide.md
  - Getting Started:
      - Installation Guide: getting-started/installation-guide.md
      - First Steps: getting-started/first-steps.md
      - FAQ: getting-started/faq.md
  - Modules:
      - Module Index: modules/module-contributor-guide.md
      - Memory Nexus: modules/memory-nexus.md
      - EchoFrame Android AI: modules/echoframe-android-ai.md
  - Core Systems:
      - Resonance Paths: core-systems/resonance-three-paths.md
      - Tool Evolution: core-systems/mnemonic-tools.md
      - Module Loader: core-systems/module-loader.md
      - Resonant Waste System: core-systems/resonant-waste-system.md
      - Mnemonic Tools: core-systems/mnemonic-tools.md
  - Game Mechanics:
      - Farming: game-mechanics/farming.md
      - Combat: game-mechanics/combat.md
      - Crafting & Processing: game-mechanics/crafting.md
      - Inventory: game-mechanics/inventory.md
      - AI & EchoFrame System: game-mechanics/ai-echoframe-system.md
  - World & Lore:
      - The Fall of Aetherion: world-lore/fall-of-aetherion.md
      - The Three Paths: world-lore/three-paths.md
      - Dimensional Index: world-lore/dimensional-contributor-guide.md
      - The Weight of What We Waste: world-lore/weight-of-waste.md
  - Contributing:
      - Contributor Guide: contributing/contributor-guide.md
      - Module Template: contributing/module-template.md
  - About:
      - Project Philosophy: about/philosophy.md
      - Credits: about/credits.md
      - Roadmap: about/roadmap.md

